<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SURESHKRISHNAN" name="Default test" tests="2" failures="0" timestamp="30 Dec 2017 12:38:15 GMT" time="0.098" errors="0">
  <testcase name="@BeforeMethod setup" time="0.0" classname="com.qa.salesforce.testcases.LoginPageTestCase">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.qa.salesforce.base.TestBase.initialization(TestBase.java:44)
	at com.qa.salesforce.testcases.LoginPageTestCase.setup(LoginPageTestCase.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:653)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @BeforeMethod setup -->
  <testcase name="@AfterMethod TearDown" time="0.0" classname="com.qa.salesforce.testcases.LoginPageTestCase">
    <skipped/>
  </testcase> <!-- @AfterMethod TearDown -->
  <testcase name="@BeforeMethod setup" time="0.0" classname="com.qa.salesforce.testcases.LoginPageTestCase">
    <skipped/>
  </testcase> <!-- @BeforeMethod setup -->
  <testcase name="@AfterMethod TearDown" time="0.0" classname="com.qa.salesforce.testcases.LoginPageTestCase">
    <skipped/>
  </testcase> <!-- @AfterMethod TearDown -->
  <testcase name="ValidateLogoTest" time="0.007" classname="com.qa.salesforce.testcases.LoginPageTestCase">
    <skipped/>
  </testcase> <!-- ValidateLogoTest -->
  <testcase name="validateLoginTest" time="0.004" classname="com.qa.salesforce.testcases.LoginPageTestCase">
    <skipped/>
  </testcase> <!-- validateLoginTest -->
</testsuite> <!-- Default test -->
